export const ORANGE = "#f5a623";
export const DARK   = "#0f1623";
export const NAVY   = "#141e30";
export const CARD   = "#1a2540";
export const MUTED  = "#8a95b0";
export const WHITE  = "#f0f4ff";

export const styles = {
  page: {
    maxWidth: 760,
    margin: "0 auto",
    padding: "56px 24px 80px",
  },
  badge: {
    display: "inline-block",
    background: "rgba(245,166,35,0.15)",
    color: ORANGE,
    borderRadius: 4,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.12em",
    padding: "3px 10px",
    marginBottom: 18,
    textTransform: "uppercase",
  },
  h1: {
    fontSize: "clamp(28px, 5vw, 44px)",
    fontWeight: 700,
    color: DARK,
    margin: "0 0 12px",
    lineHeight: 1.15,
    letterSpacing: "-0.01em",
  },
  lead: {
    color: MUTED,
    fontSize: 17,
    lineHeight: 1.7,
    marginBottom: 40,
    maxWidth: 580,
  },
  divider: {
    border: "none",
    borderTop: `1px solid rgba(245,166,35,0.12)`,
    margin: "32px 0",
  },
  card: {
    background: CARD,
    border: `1px solid rgba(245,166,35,0.1)`,
    borderRadius: 14,
    padding: "24px 28px",
    marginBottom: 16,
  },
  cardTitle: {
    color: ORANGE,
    fontWeight: 700,
    fontSize: 15,
    marginBottom: 6,
    letterSpacing: "0.02em",
  },
  cardText: {
    color: MUTED,
    fontSize: 14,
    lineHeight: 1.65,
  },
  label: {
    display: "block",
    color: MUTED,
    fontSize: 12,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    marginBottom: 6,
    marginTop: 18,
  },
  input: {
    width: "100%",
    background: CARD,
    border: `1px solid rgba(245,166,35,0.18)`,
    borderRadius: 8,
    padding: "12px 14px",
    color: WHITE,
    fontSize: 15,
    fontFamily: "'Georgia', serif",
    outline: "none",
    boxSizing: "border-box",
    transition: "border-color 0.15s",
  },
  textarea: {
    width: "100%",
    background: CARD,
    border: `1px solid rgba(245,166,35,0.18)`,
    borderRadius: 8,
    padding: "12px 14px",
    color: WHITE,
    fontSize: 15,
    fontFamily: "'Georgia', serif",
    outline: "none",
    boxSizing: "border-box",
    resize: "vertical",
    minHeight: 120,
  },
  btn: {
    marginTop: 22,
    background: ORANGE,
    color: "#1a0e00",
    border: "none",
    borderRadius: 100,
    padding: "13px 36px",
    fontWeight: 700,
    fontSize: 15,
    fontFamily: "'Georgia', serif",
    cursor: "pointer",
    letterSpacing: "0.02em",
    transition: "opacity 0.15s, transform 0.15s",
  },
  section: {
    marginBottom: 36,
  },
  h2: {
    color: ORANGE,
    fontSize: 18,
    fontWeight: 700,
    margin: "0 0 10px",
    letterSpacing: "0.02em",
  },
  p: {
    color: MUTED,
    fontSize: 15,
    lineHeight: 1.75,
    margin: "0 0 14px",
  },
  // Chat-specific
  chatBubble: (self) => ({
    display: "flex",
    justifyContent: self ? "flex-end" : "flex-start",
    marginBottom: 12,
  }),
  bubble: (self) => ({
    background: self ? ORANGE : CARD,
    color: self ? "#1a0e00" : WHITE,
    borderRadius: self ? "18px 18px 4px 18px" : "18px 18px 18px 4px",
    padding: "10px 16px",
    maxWidth: "72%",
    fontSize: 14,
    lineHeight: 1.55,
    border: self ? "none" : `1px solid rgba(245,166,35,0.1)`,
  }),
  chatWrap: {
    background: CARD,
    border: `1px solid rgba(245,166,35,0.12)`,
    borderRadius: 14,
    padding: "24px 20px 16px",
    marginBottom: 16,
    minHeight: 220,
  },
  chatInputRow: {
    display: "flex",
    gap: 10,
    marginTop: 4,
  },
  // Preferences-specific
  toggleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    background: CARD,
    border: `1px solid rgba(245,166,35,0.1)`,
    borderRadius: 10,
    padding: "16px 20px",
    marginBottom: 12,
    cursor: "pointer",
  },
  toggleKnob: (on) => ({
    width: 42,
    height: 24,
    borderRadius: 12,
    background: on ? ORANGE : "rgba(255,255,255,0.1)",
    position: "relative",
    transition: "background 0.2s",
    flexShrink: 0,
  }),
  knob: (on) => ({
    position: "absolute",
    top: 3,
    left: on ? 21 : 3,
    width: 18,
    height: 18,
    borderRadius: "50%",
    background: WHITE,
    transition: "left 0.2s",
  }),
};
